volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - banco
  frontend:
    image: nginx:1.25
    environment:
      - NGINX_PORT=80
    volumes:
    # Site
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
    # Aplicação
      - ./app:/app
    working_dir: /app
    command: ./app.sh
    networks:
      - web
      - banco
    depends_on:
      - db